package com.tinhocanhtrang.entity;
// Generated Jun 8, 2023, 11:31:01 PM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Producer generated by hbm2java
 */
@Entity
@Table(name = "PRODUCER", schema = "dbo", catalog = "THAT")
public class Producer implements java.io.Serializable {

	private String producerId;
	private String producerEmail;
	private Serializable producerName;
	private String producerPhone;
	private Set<Product> products = new HashSet<Product>(0);

	public Producer() {
	}

	public Producer(String producerId, String producerEmail, Serializable producerName, String producerPhone) {
		this.producerId = producerId;
		this.producerEmail = producerEmail;
		this.producerName = producerName;
		this.producerPhone = producerPhone;
	}

	public Producer(String producerId, String producerEmail, Serializable producerName, String producerPhone,
			Set<Product> products) {
		this.producerId = producerId;
		this.producerEmail = producerEmail;
		this.producerName = producerName;
		this.producerPhone = producerPhone;
		this.products = products;
	}

	@Id

	@Column(name = "producer_id", unique = true, nullable = false, length = 30)
	public String getProducerId() {
		return this.producerId;
	}

	public void setProducerId(String producerId) {
		this.producerId = producerId;
	}

	@Column(name = "producer_email", nullable = false, length = 50)
	public String getProducerEmail() {
		return this.producerEmail;
	}

	public void setProducerEmail(String producerEmail) {
		this.producerEmail = producerEmail;
	}

	@Column(name = "producer_name", nullable = false)
	public Serializable getProducerName() {
		return this.producerName;
	}

	public void setProducerName(Serializable producerName) {
		this.producerName = producerName;
	}

	@Column(name = "producer_phone", nullable = false, length = 11)
	public String getProducerPhone() {
		return this.producerPhone;
	}

	public void setProducerPhone(String producerPhone) {
		this.producerPhone = producerPhone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producer")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
