package com.tinhocanhtrang.entity;
// Generated Jun 5, 2023, 1:36:25 PM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Producter generated by hbm2java
 */
@Entity
@Table(name = "PRODUCTER", schema = "dbo", catalog = "THAT")
public class Producter implements java.io.Serializable {

	private String producterId;
	private String producterEmail;
	private Serializable producterName;
	private String producterPhone;
	private Set<Product> products = new HashSet<Product>(0);

	public Producter() {
	}

	public Producter(String producterId, String producterEmail, Serializable producterName, String producterPhone) {
		this.producterId = producterId;
		this.producterEmail = producterEmail;
		this.producterName = producterName;
		this.producterPhone = producterPhone;
	}

	public Producter(String producterId, String producterEmail, Serializable producterName, String producterPhone,
			Set<Product> products) {
		this.producterId = producterId;
		this.producterEmail = producterEmail;
		this.producterName = producterName;
		this.producterPhone = producterPhone;
		this.products = products;
	}

	@Id

	@Column(name = "producter_id", unique = true, nullable = false, length = 30)
	public String getProducterId() {
		return this.producterId;
	}

	public void setProducterId(String producterId) {
		this.producterId = producterId;
	}

	@Column(name = "producter_email", nullable = false, length = 50)
	public String getProducterEmail() {
		return this.producterEmail;
	}

	public void setProducterEmail(String producterEmail) {
		this.producterEmail = producterEmail;
	}

	@Column(name = "producter_name", nullable = false)
	public Serializable getProducterName() {
		return this.producterName;
	}

	public void setProducterName(Serializable producterName) {
		this.producterName = producterName;
	}

	@Column(name = "producter_phone", nullable = false, length = 11)
	public String getProducterPhone() {
		return this.producterPhone;
	}

	public void setProducterPhone(String producterPhone) {
		this.producterPhone = producterPhone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producter")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
