package com.tinhocanhtrang.entity;
// Generated Jun 5, 2023, 1:36:25 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * SpecDetail generated by hbm2java
 */
@Entity
@Table(name = "SPEC_DETAIL", schema = "dbo", catalog = "THAT")
public class SpecDetail implements java.io.Serializable {

	private SpecDetailId id;
	private Product product;
	private Spec spec;

	public SpecDetail() {
	}

	public SpecDetail(SpecDetailId id, Product product, Spec spec) {
		this.id = id;
		this.product = product;
		this.spec = spec;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "specId", column = @Column(name = "spec_id", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false, length = 20)) })
	public SpecDetailId getId() {
		return this.id;
	}

	public void setId(SpecDetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "spec_id", nullable = false, insertable = false, updatable = false)
	public Spec getSpec() {
		return this.spec;
	}

	public void setSpec(Spec spec) {
		this.spec = spec;
	}

}
