package com.tinhocanhtrang.entity;
// Generated Jun 5, 2023, 1:36:25 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * SpecDetailId generated by hbm2java
 */
@Embeddable
public class SpecDetailId implements java.io.Serializable {

	private int specId;
	private String productId;

	public SpecDetailId() {
	}

	public SpecDetailId(int specId, String productId) {
		this.specId = specId;
		this.productId = productId;
	}

	@Column(name = "spec_id", nullable = false)
	public int getSpecId() {
		return this.specId;
	}

	public void setSpecId(int specId) {
		this.specId = specId;
	}

	@Column(name = "product_id", nullable = false, length = 20)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SpecDetailId))
			return false;
		SpecDetailId castOther = (SpecDetailId) other;

		return (this.getSpecId() == castOther.getSpecId())
				&& ((this.getProductId() == castOther.getProductId()) || (this.getProductId() != null
						&& castOther.getProductId() != null && this.getProductId().equals(castOther.getProductId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSpecId();
		result = 37 * result + (getProductId() == null ? 0 : this.getProductId().hashCode());
		return result;
	}

}
