package com.tinhocanhtrang.entity;
// Generated Jun 5, 2023, 1:36:25 PM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Spec generated by hbm2java
 */
@Entity
@Table(name = "SPEC", schema = "dbo", catalog = "THAT")
public class Spec implements java.io.Serializable {

	private Integer specId;
	private Serializable specKey;
	private Serializable specValue;
	private Set<SpecDetail> specDetails = new HashSet<SpecDetail>(0);

	public Spec() {
	}

	public Spec(Serializable specKey, Serializable specValue) {
		this.specKey = specKey;
		this.specValue = specValue;
	}

	public Spec(Serializable specKey, Serializable specValue, Set<SpecDetail> specDetails) {
		this.specKey = specKey;
		this.specValue = specValue;
		this.specDetails = specDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "spec_id", unique = true, nullable = false)
	public Integer getSpecId() {
		return this.specId;
	}

	public void setSpecId(Integer specId) {
		this.specId = specId;
	}

	@Column(name = "spec_key", nullable = false)
	public Serializable getSpecKey() {
		return this.specKey;
	}

	public void setSpecKey(Serializable specKey) {
		this.specKey = specKey;
	}

	@Column(name = "spec_value", nullable = false)
	public Serializable getSpecValue() {
		return this.specValue;
	}

	public void setSpecValue(Serializable specValue) {
		this.specValue = specValue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "spec")
	public Set<SpecDetail> getSpecDetails() {
		return this.specDetails;
	}

	public void setSpecDetails(Set<SpecDetail> specDetails) {
		this.specDetails = specDetails;
	}

}
