package com.tinhocanhtrang.entity;

<<<<<<< HEAD
import java.io.Serializable;
import java.util.List;
=======
import java.util.ArrayList;
// Generated Jun 8, 2023, 11:31:01 PM by Hibernate Tools 4.3.6.Final
import java.util.List;
import org.hibernate.annotations.Nationalized;

>>>>>>> e4b0fb2891571134e15f304253a6ac6c1570fcba
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
<<<<<<< HEAD
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
=======
import lombok.ToString;
>>>>>>> e4b0fb2891571134e15f304253a6ac6c1570fcba

/**
 * Spec generated by hbm2java
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "SPEC", schema = "dbo", catalog = "THAT")
<<<<<<< HEAD
public class Spec implements Serializable {
=======
@ToString
public class Spec {
>>>>>>> e4b0fb2891571134e15f304253a6ac6c1570fcba

	private Integer specId;
	private String specKey;
	private String specValue;
	private List<Product> products;


	public Spec(String specKey, String specValue) {
		this.specKey = specKey;
		this.specValue = specValue;
	}
<<<<<<< HEAD
=======

	public Spec(String specKey, String specValue, List<Product> products) {
		this.specKey = specKey;
		this.specValue = specValue;
		this.products = products;
	}

	public Spec(Integer specId, String specKey, String specValue) {
		this.specId = specId;
		this.specKey = specKey;
		this.specValue = specValue;
	}

>>>>>>> e4b0fb2891571134e15f304253a6ac6c1570fcba
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "spec_id", unique = true, nullable = false)
	public Integer getSpecId() {
		return this.specId;
	}

	public void setSpecId(Integer specId) {
		this.specId = specId;
	}

	@Column(name = "spec_key", nullable = false)
<<<<<<< HEAD
=======
	@Nationalized
>>>>>>> e4b0fb2891571134e15f304253a6ac6c1570fcba
	public String getSpecKey() {
		return this.specKey;
	}

	public void setSpecKey(String specKey) {
		this.specKey = specKey;
	}

	@Column(name = "spec_value", nullable = false)
<<<<<<< HEAD
=======
	@Nationalized
>>>>>>> e4b0fb2891571134e15f304253a6ac6c1570fcba
	public String getSpecValue() {
		return this.specValue;
	}

	public void setSpecValue(String specValue) {
		this.specValue = specValue;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "SPEC_DETAIL", schema = "dbo", catalog = "THAT", joinColumns = {
			@JoinColumn(name = "spec_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "product_id", nullable = false, updatable = false) })
	public List<Product> getProducts() {
		return this.products;
	}

	public void setProducts(List<Product> products) {
		this.products = products;
	}

}
