package com.tinhocanhtrang.entity;
// Generated Jun 8, 2023, 11:31:01 PM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "_USER", schema = "dbo", catalog = "THAT")
public class User implements java.io.Serializable {

	private String userPhone;
	private Serializable userName;
	private String userEmail;
	private String userPassword;
	private boolean userRole;
	private Set<Bill> bills = new HashSet<Bill>(0);

	public User() {
	}

	public User(String userPhone, Serializable userName, String userEmail, String userPassword, boolean userRole) {
		this.userPhone = userPhone;
		this.userName = userName;
		this.userEmail = userEmail;
		this.userPassword = userPassword;
		this.userRole = userRole;
	}

	public User(String userPhone, Serializable userName, String userEmail, String userPassword, boolean userRole,
			Set<Bill> bills) {
		this.userPhone = userPhone;
		this.userName = userName;
		this.userEmail = userEmail;
		this.userPassword = userPassword;
		this.userRole = userRole;
		this.bills = bills;
	}

	@Id

	@Column(name = "user_phone", unique = true, nullable = false, length = 64)
	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	@Column(name = "user_name", nullable = false)
	public Serializable getUserName() {
		return this.userName;
	}

	public void setUserName(Serializable userName) {
		this.userName = userName;
	}

	@Column(name = "user_email", nullable = false, length = 50)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "user_password", nullable = false, length = 60)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "user_role", nullable = false)
	public boolean isUserRole() {
		return this.userRole;
	}

	public void setUserRole(boolean userRole) {
		this.userRole = userRole;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Bill> getBills() {
		return this.bills;
	}

	public void setBills(Set<Bill> bills) {
		this.bills = bills;
	}

}
